### PR TITLE
registering signs you in

### PR DESCRIPTION
**Pull request by Ka5hme**
registering signs you in on completion

### CODE REVIEW

**Review by Rebecca-CYLi — CHANGES_REQUESTED** [review]
did y'all forget to put the node_modules into the .gitignore? the register.css is empty

**Comment by Ka5hme** [comment]
> did y'all forget to put the node_modules into the .gitignore? the register.css is empty

we used bootstrap so a lot of the CSS is done using bootstraps className we ended up needing no additional css for the registration

**Review by Rebecca-CYLi — CHANGES_REQUESTED** [review]
now it's frontend dir with the node_modules pushed. also, register.css is still empty [x] ok, used bootstrap for css. awesome

**Review by Rebecca-CYLi — APPROVED** [review]
both dir added node_modules to ignore file, ok

**Pull request merged**
